runtime: python
env: flex
entrypoint: python main.py

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

vpc_access_connector:
    name: projects/xmas-game-388208/locations/us-west1/connectors/xmas-game-connector

env_variables:
    REDISHOST: '10.132.99.99'
    REDISPORT: '6379'